### ISSUE TITLE
port to tf V2 causing errors im unable to understand

### ISSUE THREAD

**Issue by pushtoopen** [amrit110/stereo_matching#2]
Im currently working to port your work over to tensorflow V2.0. https://github.com/pushtoopen/stereo_matching/tree/port_to_tf_v2 I've gotten a lot of the basics cleaned up, but now i've reached the end of my ability to debug, as i am not a heavy tensorflow user and am learning this now. I had to change the to_int32 calls on the sample_info array to a newer version of it tf.dtypes.cast(. i believe this is causing an issue, because now when dataset.map is called inside of dataset,py, i get the following error:

    ValueError: Index out of range using input dim 0; input has only 0 dims for '{{node strided_slice_6}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=4, ellipsis_mask=0, end_mask=4, new_axis_mask=0, shrink_axis_mask=0](strided_slice_4, strided_slice_6/stack, strided_slice_6/stack_1, strided_slice_6/stack_2)' with input shapes: [], [3], [3], [3] and with computed input tensors: input[3] = <1 1 1>.

this is with using the demo command: python main.py --dataset kitti_2015 --patch-size 37 --disparity-range 201

using
tensorflow             2.3.1
tensorflow-estimator   2.3.0
python 3.8.5
ubuntu 20.04

full traceback is

Traceback (most recent call last):
  File "main.py", line 133, in <module>
    training_dataset = Dataset(settings, patch_locations, phase='train')
  File "/home/user/esp/WORK/tensorflow/stereo_matching/lib/dataset.py", line 118, in __init__
    self.iterator = self._create_dataset_iterator(patch_locations, phase)
  File "/home/user/esp/WORK/tensorflow/stereo_matching/lib/dataset.py", line 223, in _create_dataset_iterator
    return self._create_train_iterator(patch_locations)
  File "/home/user/esp/WORK/tensorflow/stereo_matching/lib/dataset.py", line 191, in _create_train_iterator
    dataset = dataset.map(self._parse_function)
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1695, in map
    return MapDataset(self, map_func, preserve_cardinality=True)
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4041, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3371, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2938, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2906, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3065, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3364, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3299, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/user/esp/WORK/tensorflow/stereo_matching/lib/dataset.py:154 _parse_function  *
        left_patch = left_image[left_center_y -                                self._settings.half_patch_size:left_center_y +                                self._settings.half_patch_size + 1,
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:1013 _slice_helper
        return strided_slice(
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:1186 strided_slice
        op = gen_array_ops.strided_slice(
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py:10347 strided_slice
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:742 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py:591 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:3477 _create_op_internal
        ret = Operation(
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1974 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    /home/user/esp/WORK/tensorflow/tensorflow_venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Index out of range using input dim 0; input has only 0 dims for '{{node strided_slice_6}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=4, ellipsis_mask=0, end_mask=4, new_axis_mask=0, shrink_axis_mask=0](strided_slice_4, strided_slice_6/stack, strided_slice_6/stack_1, strided_slice_6/stack_2)' with input shapes: [], [3], [3], [3] and with computed input tensors: input[3] = <1 1 1>.

Don't know if you're interested in looking at this, but thanks for your time.

**Comment by pushtoopen** [comment]
This was just due to not having the models inside the folder structure properly. I'd suggest a little more detail on how the models needs to be downloaded from online and placed in the folders.
